### ISSUE TITLE
Is `.cpp` file compulsory?

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-library-manager#26]
For porting of `Adafruit_Sensor`, it only contains a `.h` file and not a `.cpp`. I would still expect the library manager to accept it as a valid library

```
main header is missing
KENMBP:Adafruit_Sensor kennethlimcp$ tree
.
├── LICENSE
├── README.md
├── library.properties
└── src
    └── Adafruit_Sensor.h
```

**Comment by monkbroc** [comment]
Header only libraries are now allowed :)
